version: 0.2
phases:
  pre_build:
      commands:
      
        - echo "hello"
        - aws --version
        - CICD_GIT_REPO= aws secretsmanager get-secret-value --secret-id bnm-k8s-pipeline | jq --raw-output .SecretString | jq -r ."CICD_GIT_REPO"
        - echo $CICD_GIT_REPO
