FROM php:8.3.2

RUN mkdir -p /var/sites/white-lotus

WORKDIR /var/sites/white-lotus

COPY . .

RUN apt-get update && apt-get install -y awscli

RUN aws s3 cp s3://unocoin-backend-api-bucket/.env .

#RUN curl -fsSL https://gist.githubusercontent.com/Shelob9/f981e8fee4e80aec383442df7838de7e/raw/427f097ae2b4c66e7ad013407ae8fe858bb849e6/php81.sh | sh


#RUN curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php

#RUN HASH=`curl -sS https://composer.github.io/installer.sig`

#RUN php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

#RUN php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

#RUN composer = "/usr/local/bin/composer"

#COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

#ENV COMPOSER_ALLOW_SUPERUSER=1

#RUN set -eux

#RUN composer install --ignore-platform-reqs --no-scripts --no-dev

#RUN docker-php-ext-install gd

#RUN docker-php-ext-install bcmath

#RUN apt-get install php8.3-gd && apt-get install php8.3-bcmath

RUN apt-get install libxml2-dev libmcrypt-dev zlib1g-dev libcurl4-openssl-dev pkg-config libssl-dev libpng-dev libjpeg62-turbo-dev freetype2-doc libzip-dev libmcrypt-dev libonig-dev -y

RUN pecl install mcrypt-1.0.7

RUN docker-php-ext-configure gd --with-jpeg

RUN docker-php-ext-install gd 

RUN docker-php-ext-install bcmath zip mysqli mbstring curl openssl

RUN docker-php-ext-enable mcrypt

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

#RUN docker-php-ext-install gd

#RUN docker-php-ext-install bcmath

#COPY composer.json composer.json

#COPY composer.lock composer.lock

RUN composer update

#RUN composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader

RUN php /var/sites/white-lotus/artisan cache:clear

RUN php /var/sites/white-lotus/artisan view:clear

RUN php /var/sites/white-lotus/artisan config:clear

RUN cd white-lotus-express

RUN apt update && apt install npm -y

RUN npm install ../bs58grscheck/ --save

RUN npm install -g @unstoppabledomains/resolution@1.16.2

RUN npm install

RUN php /var/sites/white-lotus/artisan config:cache

RUN /usr/local/apache2/bin/apachectl restart

RUN pkill screen

RUN apt update && apt install supervisor

RUN su -c "screen -d -m -S BitGo ~/bitgojs/modules/express/bin/bitgo-express --port 3080 --env prod" ubuntu
RUN su -c "screen -d -m -S notifications php /var/sites/white-lotus/artisan queue:work --queue=notifications  --tries=2" ubuntu
RUN su -c "screen -d -m -S notifications_1 php /var/sites/white-lotus/artisan queue:work --queue=notifications  --tries=2" ubuntu
RUN su -c "screen -d -m -S notifications_2 php /var/sites/white-lotus/artisan queue:work --queue=notifications  --tries=2" ubuntu

#starting white-lotus-express 
RUN su -c "screen -d -m -S whiteLotusExpress npm start --prefix /var/sites/white-lotus/white-lotus-express/" ubuntu

#Admin
RUN su -c "screen -d -m -S work_queue php /var/sites/white-lotus-admin/artisan queue:work --queue=default --tries=4" ubuntu
RUN su -c "screen -d -m -S exchange_queue php /var/sites/white-lotus-admin/artisan queue:work --queue=exchange --tries=4" ubuntu
RUN su -c "screen -d -m -S admin_notifications php /var/sites/white-lotus-admin/artisan queue:work --queue=admin_notifications --tries=4" ubuntu
RUN su -c "screen -d -m -S kyc php /var/sites/white-lotus-admin/artisan queue:work --queue=kyc --tries=2" ubuntu
RUN su -c "screen -d -m -S ome_all php /var/sites/white-lotus-admin/artisan ome_all" ubuntu

RUN su -c "screen -d -m -S push_notifications_queue /usr/local/bin/php /var/sites/white-lotus-admin/artisan queue:work --queue=push_notifications_1 --tries=4" ubuntu

RUN su -c "screen -d -m -S update_vendor_firebase_usdt php /var/sites/white-lotus-admin/artisan update_vendor_orderbook_firebase --baseCoin=USDT" ubuntu
RUN su -c "screen -d -m -S update_vendor_firebase_btc php /var/sites/white-lotus-admin/artisan update_vendor_orderbook_firebase --baseCoin=BTC" ubuntu
RUN su -c "screen -d -m -S update_vendor_firebase_inr php /var/sites/white-lotus-admin/artisan update_vendor_orderbook_firebase --baseCoin=INR" ubuntu

RUN su -c "screen -d -m -S update_vendor_usdt php /var/sites/white-lotus-admin/artisan orderbook:vendor --baseCoin=USDT" ubuntu
RUN su -c "screen -d -m -S update_vendor_btc php /var/sites/white-lotus-admin/artisan orderbook:vendor --baseCoin=BTC" ubuntu
RUN su -c "screen -d -m -S update_vendor_inr php /var/sites/white-lotus-admin/artisan orderbook:vendor --baseCoin=INR" ubuntu
#sudo su -c "screen -d -m -S update_firebase php /var/sites/white-lotus-admin/artisan update_firebase" ubuntu

RUN su -c "screen -d -m -S vendor_firebase_update_start php /var/sites/white-lotus-admin/artisan vendor_firebase_update_start" ubuntu

RUN su -c "screen -d -m -S kycdoc php /var/sites/white-lotus-admin/artisan kycDoc:validate" ubuntu


#derivatives screen
RUN su -c "screen -d -m -S ome_futures php /var/sites/white-lotus-admin/artisan ome_futures" ubuntu
RUN su -c "screen -d -m -S futures_monitor php /var/sites/white-lotus-admin/artisan futures:monitor" ubuntu
RUN su -c "screen -d -m -S future_settlement php /var/sites/white-lotus-admin/artisan future_settlement" ubuntu

RUN su -c "screen -d -m -S price_alerts php /var/sites/white-lotus-admin/artisan queue:work --queue=price_alerts --tries=1" ubuntu

RUN su -c "screen -d -m -S clevertap php /var/sites/white-lotus/artisan queue:work --queue=clevertap --tries=4" ubuntu


RUN su -c "screen -d -m -S update_firebase-1 php /var/sites/white-lotus-admin/artisan update_firebase --maxScreens=10 --modValue=-1" ubuntu

CMD ["su", "-c", "\"supervisorctl start all\""]
